Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundMethodBody:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/EvalWithLocation:
  Enabled: false
Security/Eval:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
AllCops:
  TargetRubyVersion: 3.4