[package]
name = "advent-of-code-2024-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day_1"
path = "src/1.rs"

[[bin]]
name = "day_2"
path = "src/2.rs"